
commands:
    connect: telnet localhost 7020
    hard_reset: ['/usr/local/lab-scripts/snmp_pdu_control --hostname pdu14 --command reboot --port 5 --delay 20', '/usr/local/lab-scripts/eth008_control -a 10.0.9.2 -r 3 -s onoff']
    power_off: /usr/local/lab-scripts/snmp_pdu_control --hostname pdu14 --command off --port 5 --delay 20
    power_on: ['/usr/local/lab-scripts/snmp_pdu_control --hostname pdu14 --command on --port 5 --delay 20', '/usr/local/lab-scripts/eth008_control -a 10.0.9.2 -r 3 -s onoff']
device_info: [{'board_id': '100040061d1e00e2'}]
flash_cmds_order: ['update', 'ptable', 'partition', 'hyp', 'modem', 'rpm', 'sbl1', 'sbl2', 'sec', 'tz', 'aboot', 'boot', 'rootfs', 'vendor', 'system', 'cache', 'userdata']
device_type: x15
adb_serial_number: 100040061d1e00e2
fastboot_serial_number: 100040061d1e00e2

# This attribute identifies whether a device should get into fastboot mode by
# interrupting uboot and issuing commands at the bootloader prompt.
fastboot_via_uboot: True


actions:
  deploy:
    methods:
      lxc:
      fastboot:
      u-boot:
      u-boot:
        parameters:
          bootloader_prompt: '=>'
          interrupt_prompt: 'Hit any key to stop autoboot: '
          # character needed to interrupt u-boot, single whitespace by default
          interrupt_char: " "
          send_char: False
          # method specific stanza
          fastboot:
            commands:
              - fastboot 1
    connections:
      lxc:
      serial:
  boot:
    connections:
      lxc:
      serial:
    methods:
      lxc:
      fastboot-boot-image:
      u-boot:
        parameters:
          bootloader_prompt: '=>'
          interrupt_prompt: 'Hit any key to stop autoboot: '
          boot_message: Starting kernel
          # character needed to interrupt u-boot, single whitespace by default
          interrupt_char: " "
          send_char: False
          # method specific stanza
          boot:
            commands:
              - boot

timeouts:
  actions:
    apply-overlay-image:
      minutes: 2
    dd-image:
      minutes: 10
    download_retry:
      minutes: 5
    http_download:
      minutes: 5
    lava-test-shell:
      minutes: 3
    nfs-deploy:
      minutes: 10
    power_off:
      seconds: 5
    bootloader-commands:
      minutes: 3
    bootloader-interrupt:
      seconds: 30
    umount-retry:
      seconds: 45
    auto-login-action:
      minutes: 2
    bootloader-action:
      minutes: 3
    uboot-action:
      minutes: 3
    uboot-retry:
      minutes: 3
    bootloader-retry:
      minutes: 3
  connections:
    dd-image:
      minutes: 10
    uboot-retry:
      seconds: 30
    bootloader-commands:
      seconds: 30
    auto-login-action:
      minutes: 2
    bootloader-interrupt:
      seconds: 30
